### ISSUE TITLE
file(s) at dataurl = 'http://35.188.34.63:8080/thredds/dodsC/OM4p5/'

### ISSUE THREAD

**Issue by sanAkel** [raphaeldussin/presentations#1]
Dear Raphael,

We are trying to use some of the examples and also those at your cookbook: https://mom6-analysiscookbook.readthedocs.io/en/latest/06_Horizontal_Remapping.html

The file(s) at dataurl = 'http://35.188.34.63:8080/thredds/dodsC/OM4p5/'
 aren’t accessible: firewalls and such. Our security folks are telling: ``...random server out in the google cloud might be a violation of NASA security policy somewhere…” Suspect some others users may be hit by the same issue.
 
Would you able to relocate them somewhere so that these nice examples work like a breeze! 
 
Matt Thompson (@mathomp4) has been working through them for testing xESMF and he would be able to explain better. 
 
Thanks a lot,
Santha

**Comment by raphaeldussin** [comment]
@sanAkel the file is hosted on a NOAA thredds server. You can also download it locally (5GB or so) and use the local copy in your notebook, especially if you want to use dask.

**Comment by sanAkel** [comment]
Thank you @raphaeldussin I guess our NASA VPN has be told to be _friendly_ to NOAA thredds server!
